# -*- mode: ruby -*-
# vi: set ft=ruby :

projectroot = File.dirname(__FILE__)

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.ssh.insert_key = true
  config.vm.provider "virtualbox" do |v|
        v.memory = 8192
        v.cpus = 4
    end
end
